---
- name: Setup Atlas Stream Processor for Kafka Stock Prices
  hosts: localhost
  gather_facts: false
  # become: true

  tasks:
    - name: Check if local processor details file exists
      ansible.builtin.stat:
        path: "./vars/processor_details_local.yml"
      register: local_vars_file

    - name: Include local processor details if it exists
      ansible.builtin.include_vars:
        file: "./vars/processor_details_local.yml"
      when: local_vars_file.stat.exists

    - name: Include default processor details if no local override exists
      ansible.builtin.include_vars:
        file: "./vars/processor_details.yml"
      when: not local_vars_file.stat.exists

    - name: Create Atlas Stream Processor JSON file from template
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/stream_processor.j2"
        dest: "{{ playbook_dir }}/files/stream_processor_definition.json"

    - name: Load Stream Processor definition from JSON
      ansible.builtin.set_fact:
        stream_processor_def: "{{ lookup('file', 'stream_processor_definition.json') | from_json }}"
    
    - name: List existing Atlas Stream Processors
      ansible.builtin.uri:
        url: "https://cloud.mongodb.com/api/atlas/v2/groups/{{ atlas_group_id }}/streams/{{ workspace_name }}/processors"
        method: GET
        url_username: "{{ atlas_public_key }}"
        url_password: "{{ atlas_private_key }}"
        headers:
          Accept: "application/vnd.atlas.2025-03-12+json"
        return_content: yes
      register: processor_list

    # If the API returns {"results":[{name:..}, ...]}
    - name: Does the Atlas Stream Processor already exist?
      ansible.builtin.set_fact:
        processor_exists: >-
          {{
            (processor_list.json.results | default([]))
            | selectattr('name','equalto', stream_processor_name)
            | list | length > 0
          }}

    - name: Create Atlas Stream Processor for Kafka Stock Prices
      ansible.builtin.uri:
        url: "https://cloud.mongodb.com/api/atlas/v2/groups/{{ atlas_group_id }}/streams/{{ workspace_name }}/processor"
        method: POST
        # MongoDB Atlas Programmatic API Keys (Digest auth)
        url_username: "{{ atlas_public_key }}"
        url_password: "{{ atlas_private_key }}"
        # Don't force Basic; Atlas uses HTTP Digest
        force_basic_auth: no
        # Headers from your curl
        headers:
          Accept: "application/vnd.atlas.2025-03-12+json"
          Content-Type: "application/json"
        body: "{{ stream_processor_def }}"
        body_format: json
        status_code: [200, 201, 202]   # Atlas often returns 201/202 on create
        return_content: yes
        validate_certs: yes
        timeout: 60
      register: atlas_connection_resp
      when: not processor_exists

