---
- name: Backfill materialized views for sample_analytics
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Check if local processor details file exists
      ansible.builtin.stat:
        path: "./vars/processor_details_local.yml"
      register: local_vars_file

    - name: Include local processor details if it exists
      ansible.builtin.include_vars:
        file: "./vars/processor_details_local.yml"
      when: local_vars_file.stat.exists

    - name: Include default processor details if no local override exists
      ansible.builtin.include_vars:
        file: "./vars/processor_details.yml"
      when: not local_vars_file.stat.exists

    - name: Set mongodb_uri from vars
      ansible.builtin.set_fact:
        mongodb_uri: "mongodb+srv://{{ atlas_cluster_user }}:{{ atlas_cluster_password }}@{{ atlas_cluster_uri }}/?retryWrites=true&w=majority"

    - name: Sanity check MONGODB_URI
      ansible.builtin.fail:
        msg: "Set MONGODB_URI in your environment (mongodb+srv://... or mongodb://...)."
      when: mongodb_uri | length == 0

  tasks:

    - name: Create/ensure sink indexes required by $merge.on
      ansible.builtin.shell: |
        mongosh "{{ mongodb_uri }}" --quiet <<'JS'
        use {{ sink_db }};

         db.customers_ref.createIndex(
          { _id: 1 }
        );

        db.accounts_ref.createIndex(
          { _id: 1 }
        );
        
        // These match the $merge.on you use in ASP (adjust if different)
        db.transactions_flat.createIndex(
          { account_id: 1, date: 1, symbol: 1, amount: 1, price: 1 },
          { unique: true, name: "unique_account_id_1_date_1_symbol_1_amount_1_price_1" }
        );

        db.transactions_enriched.createIndex(
          { account_id: 1, date: 1 },
          { unique: true, name: "unique_account_id_1_date_1" }
        );
        JS
      args:
        executable: /bin/bash